
  CREATE TABLE "INVUSER"."INV_MASTER_PROFILE" 
   (	"MASTER_PROFILE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED_BY" VARCHAR2(255 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"REMARK" VARCHAR2(1500 BYTE), 
	"FLAG_VIP" NUMBER(10,0), 
	"LUCKY_NUMBER" VARCHAR2(255 BYTE), 
	"LUCKY_NUMBER_LEVEL" NUMBER(10,0), 
	"NON_CHARGE" VARCHAR2(255 BYTE), 
	"OWNER" NUMBER(10,0), 
	"PAYMENT_MODE" NUMBER(10,0), 
	"PREVIOUS_STATUS" NUMBER(10,0), 
	"SALE_CHANEL" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"STATUS_BEFORE_PREVIOUS" NUMBER(10,0), 
	"MASTER_ID" NUMBER(19,0), 
	"OM_OWNER" VARCHAR2(255 BYTE), 
	"OM_RESERVED_TYPE" VARCHAR2(255 BYTE), 
	"OM_RESERVED_DATE" TIMESTAMP (6), 
	"IS_TER_OCS" VARCHAR2(255 BYTE), 
	 PRIMARY KEY ("MASTER_PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INV_DATA"  ENABLE, 
	 CONSTRAINT "FKKAO5SEKRTK8HFUYOYBIPH1I1X" FOREIGN KEY ("MASTER_ID")
	  REFERENCES "INVUSER"."INV_MASTER" ("MASTER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INV_DATA" ;

  CREATE INDEX "INVUSER"."INV_MASTER_PROFILE_IDX" ON "INVUSER"."INV_MASTER_PROFILE" ("MASTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INV_DATA" ;
