CREATE SEQUENCE INVMASTER_SEQ;
CREATE SEQUENCE INVMAPPING_SEQ;
CREATE SEQUENCE INVMASTERPROFILE_SEQ;
CREATE SEQUENCE INVLOG_SEQ;
CREATE SEQUENCE INVLOGNUMBER_SEQ;

grant select on INVMASTER_SEQ To invmig;
grant select on INVMAPPING_SEQ To invmig;
grant select on INVMASTERPROFILE_SEQ To invmig;
grant select on INVLOG_SEQ To invmig;
grant select on INVLOGNUMBER_SEQ To invmig;


GRANT ALL ON INV_MAPPING TO invmig;
GRANT ALL ON INV_MASTER TO invmig;
GRANT ALL ON INV_MASTER_PROFILE TO invmig;
GRANT ALL ON INV_LOG TO invmig;
GRANT ALL ON INV_LOG_NUMBER TO invmig;
CREATE INDEX INV_MAPPING_INDEX1 ON INV_MAPPING (EXTERNAL_ID, IMSI);

ALTER TABLE INV_LOG_NUMBER MODIFY (STATUS VARCHAR2(3 BYTE) );
ALTER TABLE INV_LOG_NUMBER MODIFY (STATUS_PREVIOUS VARCHAR2(3 BYTE) );